-- PIMCORE-3231
INSERT INTO USER_RIGHT (ID, IDENTIFIER, DESCRIPTION, PARENTID, ISMASTERDATA, CREATIONDATE, LASTMODIFIED, UPDATEUSER, CREATEUSER) VALUES (200031, 'Attributes - Import/Export Tab View', null, 200000, 1, sysdate, sysdate, 1, 1);
INSERT INTO USER_ROLE_USER_RIGHT_REL select seq_basic_id.nextval, userrole, 200031, sysdate, sysdate, 1, 1 FROM USER_ROLE_USER_RIGHT_REL WHERE USERRIGHT = 310012;
INSERT INTO USER_ROLE_USER_RIGHT_REL select seq_basic_id.nextval, userrole, 200031, sysdate, sysdate, 1, 1 FROM USER_ROLE_USER_RIGHT_REL WHERE USERRIGHT = 310014;
INSERT INTO USER_ROLE_USER_RIGHT_REL select seq_basic_id.nextval, userrole, 200031, sysdate, sysdate, 1, 1 FROM USER_ROLE_USER_RIGHT_REL WHERE USERRIGHT = 310031;

-- PIMCORE-3276
CREATE TABLE PROCESS_LOG(
    ID                  NUMBER(19)              NOT NULL,
    REFTYPE             VARCHAR2(254 CHAR)      NOT NULL,
    REFID               NUMBER(19)              NOT NULL,
    SUBPROCESS          VARCHAR2(254 CHAR),
    KEY                 VARCHAR2(1024 CHAR)     NOT NULL,
    VALUE               VARCHAR2(4000 CHAR)     NOT NULL,
    CREATIONDATE        TIMESTAMP               NOT NULL,
    LASTMODIFIED        TIMESTAMP               NOT NULL,
    CREATEUSER          NUMBER(19)              NOT NULL,
    UPDATEUSER          NUMBER(19)              NOT NULL,
    CONSTRAINT PK_PLOG PRIMARY KEY (ID),
    CONSTRAINT UC_PLOG UNIQUE (REFTYPE,REFID,SUBPROCESS,KEY),
    CONSTRAINT FK_PLOG_JHIST FOREIGN KEY(REFID)
        REFERENCES JOB_HISTORY(ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_PLOG_UU FOREIGN KEY(UPDATEUSER)
        REFERENCES USERS(ID),
    CONSTRAINT FK_PLOG_CU FOREIGN KEY(CREATEUSER)
        REFERENCES USERS(ID)
);

-- PIMCORE-3236
INSERT INTO USER_RIGHT (ID, IDENTIFIER, DESCRIPTION, PARENTID, ISMASTERDATA, CREATIONDATE, LASTMODIFIED, UPDATEUSER, CREATEUSER) VALUES (475000, 'REST Resource Rights', null, 100000, 1, sysdate, sysdate, 1, 1);
INSERT INTO USER_RIGHT (ID, IDENTIFIER, DESCRIPTION, PARENTID, ISMASTERDATA, CREATIONDATE, LASTMODIFIED, UPDATEUSER, CREATEUSER) VALUES (475001, 'REST Resource - Validation', null, 475000, 1, sysdate, sysdate, 1, 1);

--PIMCORE-3042 (READ the corresponding ticket and expect setups where might exist different existing indices)
-- Removed index
DROP INDEX IDX_ART_ASSET_REL_1;

-- Replaced index on ARTICLE_AV_ATTRIBUTE_VALUE_REL
DROP INDEX IDX_ART_AV_REL_FK;
CREATE INDEX IDX_ART_AV_ATTR_VAL_01 ON ARTICLE_AV_ATTRIBUTE_VALUE_REL (ARTICLEAV, ATTRIBUTEVALUE, COMPOSITIONVALUE);

-- PLEASE REVIEW THE FOLLOWING ARTICLE_AV INDICES
--DROP INDEX ARTICLE_AV_IDX_2; -- columns were  (ATTRIBUTE, PLAINVALUE, CLIENT)
--DROP INDEX ARTICLE_AV_IDX_3; -- columns were (ARTICLE, CLIENT, ATTRIBUTE, FREETEXT)

CREATE INDEX ARTICLE_AV_IDX_10 ON ARTICLE_AV  (PLAINVALUE, ATTRIBUTE, ARTICLE);
CREATE INDEX ARTICLE_AV_IDX_11 ON ARTICLE_AV  (ATTRIBUTEVALUE, ATTRIBUTE, ARTICLE);
CREATE INDEX ARTICLE_AV_IDX_12 ON ARTICLE_AV  (DECIMALVALUE, ATTRIBUTE, ARTICLE);
CREATE INDEX ARTICLE_AV_IDX_13 ON ARTICLE_AV  (NUMBERVALUE, ATTRIBUTE, ARTICLE);
CREATE INDEX ARTICLE_AV_IDX_14 ON ARTICLE_AV  (FREETEXT, ATTRIBUTE, ARTICLE);
CREATE INDEX ARTICLE_AV_IDX_15 ON ARTICLE_AV  (ATTRIBUTE, BOOLEANVALUE, ARTICLE);

-- REMOVE ALL FK on updateUser & createUser
DROP INDEX I_FK_ARTICLE_24;
DROP INDEX I_FK_ARTICLE_26;
DROP INDEX I_FK_AARV_CU;
DROP INDEX I_FK_AARV_UU;
DROP INDEX I_FK_ARTICLE_AV_72;
DROP INDEX I_FK_ARTICLE_AV_73;
DROP INDEX I_FK_ART_AV_ATTR_VAL_REL_322;
DROP INDEX I_FK_ART_AV_ATTR_VAL_REL_323;
DROP INDEX I_FK_ARTICLE_CSG_REL_145;
DROP INDEX I_FK_ARTICLE_CSG_REL_146;
DROP INDEX I_FK_ARTICLE_DETAIL_TAB_190;
DROP INDEX I_FK_ARTICLE_DETAIL_TAB_191;
DROP INDEX I_FK_ART_DIM_2;
DROP INDEX I_FK_ART_DIM_3;
DROP INDEX I_ART_NOTE_2;
DROP INDEX I_ART_NOTE_3;
DROP INDEX I_FK_ARTICLE_PRICE_112;
DROP INDEX I_FK_ARTICLE_PRICE_113;
DROP INDEX I_FK_ARTDETAILTAB_ASSET_255;
DROP INDEX I_FK_ARTDETAILTAB_ASSET_256;
DROP INDEX I_FK_ASSET_216;
DROP INDEX I_FK_ASSET_217;
DROP INDEX I_FK_ATTRIBUTE_53;
DROP INDEX I_FK_ATTRIBUTE_55;
DROP INDEX I_FK_ATTRIBUTE_VALUE_148;
DROP INDEX I_FK_ATTRIBUTE_VALUE_149;
DROP INDEX I_FK_CAT_NODE_121;
DROP INDEX I_FK_CAT_NODE_122;
DROP INDEX I_FK_CLIENT_14;
DROP INDEX I_FK_CLIENT_16;
DROP INDEX I_FK_CLIENT_LOCALE_REL_175;
DROP INDEX I_FK_CLIENT_LOCALE_REL_176;
DROP INDEX I_FK_CONDITION_60;
DROP INDEX I_FK_CONDITION_61;
DROP INDEX I_FK_EVENT_DETAIL_108;
DROP INDEX I_FK_EVENT_DETAIL_109;
DROP INDEX I_FK_IMPACT_TRANSITION_177;
DROP INDEX I_FK_IMPACT_TRANSITION_178;
DROP INDEX I_FK_JAVASCRIPT_PARAMS_185;
DROP INDEX I_FK_JAVASCRIPT_PARAMS_186;
DROP INDEX I_FK_JAVASCRIPT_RULE_161;
DROP INDEX I_FK_JAVASCRIPT_RULE_162;
DROP INDEX I_FK_LOCALE_17;
DROP INDEX I_FK_LOCALE_18;
DROP INDEX I_FK_LOCALE_FREETEXT_163;
DROP INDEX I_FK_LOCALE_FREETEXT_164;
DROP INDEX I_FK_LOCALE_LOOKUPTEXT_187;
DROP INDEX I_FK_LOCALE_LOOKUPTEXT_188;
DROP INDEX I_FK_LOCALE_TEXT_94;
DROP INDEX I_FK_LOCALE_TEXT_95;
DROP INDEX I_FK_NODE_ARTICLE_REL_167;
DROP INDEX I_FK_NODE_ARTICLE_REL_168;
DROP INDEX I_FK_NODE_ATTRIBUTE_REL_202;
DROP INDEX I_FK_NODE_ATTRIBUTE_REL_204;
DROP INDEX I_FK_NODE_ATTR_REL_CONFIG_299;
DROP INDEX I_FK_NODE_ATTR_REL_CONFIG_300;
DROP INDEX I_FK_NODE_AV_34;
DROP INDEX I_FK_NODE_AV_36;
DROP INDEX I_FK_NODE_NODE_REL_124;
DROP INDEX I_FK_NODE_NODE_REL_125;
DROP INDEX I_FK_REPORT_21;
DROP INDEX I_FK_REPORT_23;
DROP INDEX I_FK_SKN_POOL_46;
DROP INDEX I_FK_SKN_POOL_47;
DROP INDEX I_FK_TYPE_6;
DROP INDEX I_FK_TYPE_4;
DROP INDEX I_FK_TYPE_TYPE_63;
DROP INDEX I_FK_TYPE_TYPE_64;
DROP INDEX I_FK_UOM_1;
DROP INDEX I_FK_UOM_2;
DROP INDEX I_FK_UOM_CONVERSION_137;
DROP INDEX I_FK_UOM_CONVERSION_139;
DROP INDEX I_FK_USER_RIGHT_90;
DROP INDEX I_FK_USER_RIGHT_91;
DROP INDEX I_FK_USER_ROLE_66;
DROP INDEX I_FK_USER_ROLE_67;
DROP INDEX I_FK_USER_RL_USR_RGHT_REL_295;
DROP INDEX I_FK_USER_RL_USR_RGHT_REL_293;
DROP INDEX I_FK_USER_USER_ROLE_REL_207;
DROP INDEX I_FK_USER_USER_ROLE_REL_205;
DROP INDEX I_FK_USERS_12;
DROP INDEX I_FK_USERS_13;
DROP INDEX I_FK_VERSION_44;
DROP INDEX I_FK_WORKFLOW_48;
DROP INDEX I_FK_WORKFLOW_49;
DROP INDEX I_FK_WORKLIST_52;
DROP INDEX I_FK_WORKLIST_50;
DROP INDEX I_FK_WORKLIST_ENTRY_141;
DROP INDEX I_FK_WORKLIST_ENTRY_142;
DROP INDEX I_FK_VERSION_39;

-- ID
UPDATE SERVER_PROPERTY SET PROPERTYVALUE='v4.2.01', LASTMODIFIED=sysdate WHERE PROPERTYKEY='server.id';
