-- PIMCORE-3084
ALTER TABLE ATTRIBUTE_VALUE_AV_REL ADD OPERATOR VARCHAR2(254 CHAR) DEFAULT 'EQUALS' NOT NULL;
ALTER TABLE ATTRIBUTE_VALUE_AV_REL ADD CONDITIONGROUP NUMBER(19);

ALTER TABLE ATTRIBUTE_VALUE_AV_REL DROP CONSTRAINT UC_AVAVREL;
ALTER TABLE ATTRIBUTE_VALUE_AV_REL ADD CONSTRAINT UC_AVAVREL UNIQUE (ATTRIBUTE, ATTRIBUTEVALUE, RELATEDATTRIBUTE, RELATEDAV, CONDITIONGROUP);

-- PIMCORE-2889
ALTER TABLE PUBLICATION ADD CONSTRAINT UC_PUBLICATION UNIQUE (IDENTIFIER);
ALTER TABLE VERSION ADD CONSTRAINT UC_VERSION UNIQUE (IDENTIFIER);
ALTER TABLE ASSET_TREE ADD CONSTRAINT UC_ASSET_TREE UNIQUE (IDENTIFIER);
ALTER TABLE ASSET_NODE ADD CONSTRAINT UC_ANODE_ATREE UNIQUE (ROOTNODE, IDENTIFIER);

-- PIMCORE-2890
ALTER TABLE ASSET_NODE ADD VALIDFROM DATE;
ALTER TABLE ASSET_NODE ADD VALIDUNTIL DATE;

ALTER TABLE ASSET_NODE ADD USERRIGHT NUMBER(19);
ALTER TABLE ASSET_NODE ADD CONSTRAINT FK_ANODE_RIGHT FOREIGN KEY(USERRIGHT) REFERENCES USER_RIGHT(ID);

ALTER TABLE ASSET_TREE ADD USERRIGHT NUMBER(19);
ALTER TABLE ASSET_TREE ADD CONSTRAINT FK_ATREE_RIGHT FOREIGN KEY(USERRIGHT) REFERENCES USER_RIGHT(ID);

INSERT INTO USER_RIGHT (ID, IDENTIFIER, DESCRIPTION, PARENTID, ISMASTERDATA, CREATIONDATE, LASTMODIFIED, UPDATEUSER, CREATEUSER) VALUES (450013, 'Asset Structures Usage - Menu Button Change Validity', null, 450000, 1, sysdate, sysdate, 1, 1);
INSERT INTO USER_ROLE_USER_RIGHT_REL select seq_basic_id.nextval, userrole, 450013, sysdate, sysdate, 1, 1 FROM USER_ROLE_USER_RIGHT_REL WHERE userright = 450000;

-- ID
UPDATE SERVER_PROPERTY SET PROPERTYVALUE='v4.0.14', LASTMODIFIED=sysdate WHERE PROPERTYKEY='server.id';
